version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
          time: '07:00'
          timezone: 'America/New_York'
      open-pull-requests-limit: 25
      groups:
        typescript-ecosystem:
          patterns:
            - 'typescript'
            - '@typescript-eslint/*'
        docusaurus:
          patterns:
            - '@docusaurus/*'
      commit-message:
        prefix: 'dependabot'
        prefix-development: 'dependabot'
        include: 'scope'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
          time: '07:00'
          timezone: 'America/New_York'
      open-pull-requests-limit: 25
      commit-message:
          prefix: 'dependabot'
          include: 'scope'
