repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: just-fmt
        name: just --fmt
        entry: sh -c 'for file do just --fmt --justfile "$file" || exit; done' --
        language: system
        files: '(?i)(^|/)\.?justfile$|\.just$'
        types: [file]
      - id: prettier
        name: prettier
        entry: npx prettier --write --ignore-unknown
        language: system
        types: [text]
        files: \.(json|json5|yaml|yml|md|html|css|scss)$
