name: Daily Deployment

on:
  schedule:
    # 8 AM EST / 9 AM EDT
    - cron: "0 13 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "daily-deployment"
  cancel-in-progress: true

jobs:
  update-and-deploy:
    name: Update Submodules and Deploy
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git submodule update --remote --recursive

          # Check if there are any changes
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Update submodules"
            git push
          else
            echo "No submodule updates detected"
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - uses: jdx/mise-action@v2

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          just download-data-ci
          just build

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
